SUMMARY = "DrumGizmo is drum plugin and stand-alone application"
HOMEPAGE = "https://www.drumgizmo.org"
LICENSE = "LGPLv3"
LIC_FILES_CHKSUM = "file://COPYING;md5=e6a600fd5e1d9cbde2d983680233ad02"

SRC_URI = " \
    http://www.drumgizmo.org/releases/${BPN}-${PV}/${BPN}-${PV}.tar.gz \
"
SRC_URI[md5sum] = "48ffd5f665254172db234c042b65ecdc"
SRC_URI[sha256sum] = "a62f93a57b79db7572c51e5e76453a5035925f952bb53f8cd6035f72b8c76f8d"
PV = "0.9.15"
