SUMMARY = "DrumGizmo is drum plugin and stand-alone application"
HOMEPAGE = "https://www.drumgizmo.org"
LICENSE = "LGPLv3"
LIC_FILES_CHKSUM = "file://COPYING;md5=e6a600fd5e1d9cbde2d983680233ad02"

SRC_URI = " \
    http://www.drumgizmo.org/releases/${BPN}-${PV}/${BPN}-${PV}.tar.gz \
"
SRC_URI[md5sum] = "028a9c352e6c44d4d56d73b84d640941"
SRC_URI[sha256sum] = "e443a5fbb5d1fbb4386b551120d4fdde23174948b7efd79092ea79f0257c52e0"
PV = "0.9.14"
