SUMMARY = "DrumGizmo is drum plugin and stand-alone application"
HOMEPAGE = "https://www.drumgizmo.org"
LICENSE = "LGPLv3"
LIC_FILES_CHKSUM = "file://COPYING;md5=e6a600fd5e1d9cbde2d983680233ad02"

SRC_URI = " \
    http://www.drumgizmo.org/releases/${BPN}-${PV}/${BPN}-${PV}.tar.gz \
"
SRC_URI[md5sum] = "86e4239f1eb59e8b77c7d13edc24f93b"
SRC_URI[sha256sum] = "8f76b58785186ac02337b9248003ec1a459a801d3003619fd32fde976c307947"
PV = "0.9.16"
